spring.application.name=settlementFundingSelector

spring.datasource.url=jdbc:postgresql://localhost:5432/settlement_db
spring.datasource.username=settlement_user
spring.datasource.password=settlement_password

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true